import type {
  Course,
  Quiz,
  Quest,
  Job,
  Achievement,
  MarketplaceItem,
} from "../types.js";

export const SEED_COURSES: Course[] = [
  {
    id: "course-1",
    title: "JavaScript Mastery",
    description: "Master modern JavaScript from fundamentals to advanced patterns including ES2024 features, async/await, and functional programming.",
    instructor: "Alex Johnson",
    category: "Programming",
    difficulty: "beginner",
    xpReward: 500,
    coinReward: 100,
    thumbnail: "https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=400",
    rating: 4.8,
    duration: "12h 30m",
    tags: ["javascript", "web", "frontend", "es2024"],
    enrolledCount: 1240,
    createdAt: "2025-01-10T00:00:00.000Z",
    chapters: [
      { id: "ch-1-1", title: "Variables & Data Types", duration: "45m", order: 1, content: "Learn about var, let, const, and JavaScript's type system.", xpReward: 50, hasQuiz: true },
      { id: "ch-1-2", title: "Functions & Closures", duration: "60m", order: 2, content: "Deep dive into function declarations, expressions, arrow functions, and closures.", xpReward: 60, hasQuiz: true },
      { id: "ch-1-3", title: "Promises & Async/Await", duration: "75m", order: 3, content: "Master asynchronous JavaScript with Promises, async/await, and error handling.", xpReward: 80, hasQuiz: true },
      { id: "ch-1-4", title: "ES2024 Features", duration: "50m", order: 4, content: "Explore the latest JavaScript features including temporal, pattern matching, and more.", xpReward: 70, hasQuiz: false },
      { id: "ch-1-5", title: "Functional Programming", duration: "90m", order: 5, content: "Apply functional programming paradigms: map, filter, reduce, and composition.", xpReward: 100, hasQuiz: true },
    ],
  },
  {
    id: "course-2",
    title: "React 19 Deep Dive",
    description: "Build production-grade React apps with React 19, Server Components, Actions, and the latest concurrent features.",
    instructor: "Sarah Chen",
    category: "Frontend",
    difficulty: "intermediate",
    xpReward: 750,
    coinReward: 150,
    thumbnail: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=400",
    rating: 4.9,
    duration: "18h 45m",
    tags: ["react", "typescript", "frontend", "hooks"],
    enrolledCount: 980,
    createdAt: "2025-02-01T00:00:00.000Z",
    chapters: [
      { id: "ch-2-1", title: "React 19 New Features", duration: "60m", order: 1, content: "Explore Actions, use() hook, and new React compiler optimizations.", xpReward: 70, hasQuiz: true },
      { id: "ch-2-2", title: "Server Components", duration: "90m", order: 2, content: "Build efficient server-rendered components with streaming and Suspense.", xpReward: 100, hasQuiz: true },
      { id: "ch-2-3", title: "Advanced Hooks", duration: "75m", order: 3, content: "Master useTransition, useDeferredValue, useOptimistic, and custom hooks.", xpReward: 90, hasQuiz: true },
      { id: "ch-2-4", title: "State Management", duration: "80m", order: 4, content: "Compare Zustand, Jotai, Redux Toolkit, and React's built-in state solutions.", xpReward: 85, hasQuiz: false },
      { id: "ch-2-5", title: "Performance Optimization", duration: "70m", order: 5, content: "Profile and optimize React apps with the React DevTools and best practices.", xpReward: 95, hasQuiz: true },
    ],
  },
  {
    id: "course-3",
    title: "Python for Data Science",
    description: "Go from Python basics to building ML models with NumPy, Pandas, Scikit-learn, and data visualization.",
    instructor: "Dr. Priya Nair",
    category: "Data Science",
    difficulty: "beginner",
    xpReward: 600,
    coinReward: 120,
    thumbnail: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=400",
    rating: 4.7,
    duration: "20h 00m",
    tags: ["python", "data-science", "ml", "pandas"],
    enrolledCount: 1560,
    createdAt: "2025-01-20T00:00:00.000Z",
    chapters: [
      { id: "ch-3-1", title: "Python Fundamentals", duration: "60m", order: 1, content: "Variables, control flow, functions, and OOP in Python.", xpReward: 50, hasQuiz: true },
      { id: "ch-3-2", title: "NumPy & Arrays", duration: "75m", order: 2, content: "Efficient numerical computing with NumPy arrays and broadcasting.", xpReward: 70, hasQuiz: true },
      { id: "ch-3-3", title: "Pandas DataFrames", duration: "90m", order: 3, content: "Data manipulation, cleaning, and analysis with Pandas.", xpReward: 80, hasQuiz: true },
      { id: "ch-3-4", title: "Data Visualization", duration: "60m", order: 4, content: "Create compelling visualizations with Matplotlib and Seaborn.", xpReward: 65, hasQuiz: false },
      { id: "ch-3-5", title: "Machine Learning Basics", duration: "120m", order: 5, content: "Build your first ML models with Scikit-learn: regression, classification, clustering.", xpReward: 120, hasQuiz: true },
    ],
  },
  {
    id: "course-4",
    title: "UI/UX Design Principles",
    description: "Learn professional design thinking, Figma mastery, and how to create delightful user experiences.",
    instructor: "Marco Rivera",
    category: "Design",
    difficulty: "beginner",
    xpReward: 450,
    coinReward: 90,
    thumbnail: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400",
    rating: 4.6,
    duration: "10h 15m",
    tags: ["design", "ux", "figma", "prototyping"],
    enrolledCount: 870,
    createdAt: "2025-02-15T00:00:00.000Z",
    chapters: [
      { id: "ch-4-1", title: "Design Thinking", duration: "45m", order: 1, content: "Empathize, define, ideate, prototype, and test design solutions.", xpReward: 50, hasQuiz: true },
      { id: "ch-4-2", title: "Color & Typography", duration: "60m", order: 2, content: "Master color theory, font pairing, and visual hierarchy.", xpReward: 60, hasQuiz: false },
      { id: "ch-4-3", title: "Figma Masterclass", duration: "90m", order: 3, content: "Components, auto layout, prototyping, and handoff in Figma.", xpReward: 90, hasQuiz: true },
      { id: "ch-4-4", title: "Accessibility & Inclusive Design", duration: "45m", order: 4, content: "WCAG guidelines, contrast ratios, and designing for everyone.", xpReward: 60, hasQuiz: false },
    ],
  },
  {
    id: "course-5",
    title: "SQL & Database Design",
    description: "Master relational databases, complex queries, indexing strategies, and PostgreSQL advanced features.",
    instructor: "James Park",
    category: "Backend",
    difficulty: "intermediate",
    xpReward: 550,
    coinReward: 110,
    thumbnail: "https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=400",
    rating: 4.7,
    duration: "14h 00m",
    tags: ["sql", "postgresql", "database", "backend"],
    enrolledCount: 720,
    createdAt: "2025-03-01T00:00:00.000Z",
    chapters: [
      { id: "ch-5-1", title: "SQL Fundamentals", duration: "60m", order: 1, content: "SELECT, INSERT, UPDATE, DELETE, and basic JOINs.", xpReward: 50, hasQuiz: true },
      { id: "ch-5-2", title: "Advanced Queries", duration: "80m", order: 2, content: "Subqueries, CTEs, window functions, and aggregations.", xpReward: 80, hasQuiz: true },
      { id: "ch-5-3", title: "Database Design", duration: "70m", order: 3, content: "Normalization, ER diagrams, and schema design best practices.", xpReward: 75, hasQuiz: true },
      { id: "ch-5-4", title: "Indexing & Performance", duration: "60m", order: 4, content: "Query optimization, execution plans, and index strategies.", xpReward: 85, hasQuiz: false },
    ],
  },
  {
    id: "course-6",
    title: "Machine Learning Fundamentals",
    description: "Build and deploy ML models using scikit-learn, TensorFlow, and modern MLOps practices.",
    instructor: "Dr. Aisha Rahman",
    category: "AI/ML",
    difficulty: "advanced",
    xpReward: 1000,
    coinReward: 200,
    thumbnail: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=400",
    rating: 4.9,
    duration: "25h 30m",
    tags: ["ml", "tensorflow", "neural-networks", "ai"],
    enrolledCount: 640,
    createdAt: "2025-03-10T00:00:00.000Z",
    chapters: [
      { id: "ch-6-1", title: "Supervised Learning", duration: "90m", order: 1, content: "Linear regression, logistic regression, SVMs, and decision trees.", xpReward: 100, hasQuiz: true },
      { id: "ch-6-2", title: "Neural Networks", duration: "120m", order: 2, content: "Perceptrons, backpropagation, and building NNs from scratch.", xpReward: 130, hasQuiz: true },
      { id: "ch-6-3", title: "Deep Learning with TensorFlow", duration: "150m", order: 3, content: "CNNs, RNNs, transformers, and transfer learning.", xpReward: 150, hasQuiz: true },
      { id: "ch-6-4", title: "Model Evaluation & Tuning", duration: "80m", order: 4, content: "Cross-validation, hyperparameter tuning, and avoiding overfitting.", xpReward: 90, hasQuiz: false },
      { id: "ch-6-5", title: "MLOps & Deployment", duration: "100m", order: 5, content: "Model serving, monitoring, and CI/CD pipelines for ML.", xpReward: 120, hasQuiz: true },
    ],
  },
];

export const SEED_QUIZZES: Quiz[] = [
  {
    id: "quiz-1-1",
    courseId: "course-1",
    chapterId: "ch-1-1",
    title: "JavaScript Basics Quiz",
    timeLimit: 300,
    questions: [
      {
        id: "q-1-1-1",
        text: "Which keyword declares a block-scoped variable?",
        options: ["var", "let", "function", "static"],
        correctIndex: 1,
        explanation: "`let` declares a block-scoped variable, while `var` is function-scoped.",
        xpReward: 10,
      },
      {
        id: "q-1-1-2",
        text: "What does `typeof null` return?",
        options: ["'null'", "'undefined'", "'object'", "'boolean'"],
        correctIndex: 2,
        explanation: "This is a famous JavaScript quirk — `typeof null` returns 'object' due to a legacy bug.",
        xpReward: 15,
      },
      {
        id: "q-1-1-3",
        text: "Which of these is NOT a primitive type in JavaScript?",
        options: ["string", "number", "object", "bigint"],
        correctIndex: 2,
        explanation: "Objects are reference types, not primitives. Primitives include string, number, boolean, null, undefined, symbol, and bigint.",
        xpReward: 10,
      },
    ],
  },
  {
    id: "quiz-1-2",
    courseId: "course-1",
    chapterId: "ch-1-2",
    title: "Functions & Closures Quiz",
    timeLimit: 300,
    questions: [
      {
        id: "q-1-2-1",
        text: "What is a closure?",
        options: [
          "A function with no return value",
          "A function that retains access to its outer scope after the outer function returns",
          "A sealed object",
          "A function called immediately",
        ],
        correctIndex: 1,
        explanation: "A closure is a function that 'closes over' variables from its enclosing scope, retaining access even after the enclosing function has returned.",
        xpReward: 20,
      },
      {
        id: "q-1-2-2",
        text: "Arrow functions differ from regular functions in that they:",
        options: [
          "Cannot accept parameters",
          "Cannot return values",
          "Do not have their own `this` binding",
          "Cannot be assigned to variables",
        ],
        correctIndex: 2,
        explanation: "Arrow functions inherit `this` from their enclosing lexical scope, whereas regular functions have their own `this` based on how they're called.",
        xpReward: 15,
      },
    ],
  },
  {
    id: "quiz-2-1",
    courseId: "course-2",
    chapterId: "ch-2-1",
    title: "React 19 Features Quiz",
    timeLimit: 300,
    questions: [
      {
        id: "q-2-1-1",
        text: "What is the new `use()` hook in React 19 used for?",
        options: [
          "Replacing useState",
          "Reading the value of a Promise or Context directly during render",
          "Creating side effects",
          "Memoizing expensive calculations",
        ],
        correctIndex: 1,
        explanation: "The `use()` hook lets you read a Promise or Context value directly in render, and can be called conditionally.",
        xpReward: 20,
      },
      {
        id: "q-2-1-2",
        text: "React Actions allow you to:",
        options: [
          "Dispatch Redux actions",
          "Handle async transitions with pending/error states automatically",
          "Replace useEffect",
          "Create global stores",
        ],
        correctIndex: 1,
        explanation: "React Actions integrate with transitions to handle async mutations, automatically managing pending and error states.",
        xpReward: 15,
      },
    ],
  },
  {
    id: "quiz-3-1",
    courseId: "course-3",
    chapterId: "ch-3-1",
    title: "Python Fundamentals Quiz",
    timeLimit: 240,
    questions: [
      {
        id: "q-3-1-1",
        text: "What is the output of `type([])` in Python?",
        options: ["<class 'tuple'>", "<class 'list'>", "<class 'array'>", "<class 'dict'>"],
        correctIndex: 1,
        explanation: "`[]` creates an empty list, so `type([])` returns `<class 'list'>`.",
        xpReward: 10,
      },
      {
        id: "q-3-1-2",
        text: "Which of these is a mutable data type in Python?",
        options: ["tuple", "string", "list", "frozenset"],
        correctIndex: 2,
        explanation: "Lists are mutable (can be changed after creation). Tuples, strings, and frozensets are immutable.",
        xpReward: 10,
      },
    ],
  },
];

export const SEED_QUESTS: Quest[] = [
  {
    id: "quest-1",
    title: "Code Warrior",
    description: "Complete 3 JavaScript exercises today",
    type: "daily",
    xp: 150,
    coins: 30,
    target: 3,
    icon: "⚔️",
    tags: ["javascript", "coding"],
  },
  {
    id: "quest-2",
    title: "Knowledge Seeker",
    description: "Watch 5 video lectures this week",
    type: "weekly",
    xp: 400,
    coins: 80,
    target: 5,
    icon: "📚",
    tags: ["learning", "video"],
  },
  {
    id: "quest-3",
    title: "The Grand Scholar",
    description: "Complete an entire course from start to finish",
    type: "epic",
    xp: 1000,
    coins: 250,
    target: 1,
    icon: "🏆",
    tags: ["course", "completion"],
  },
  {
    id: "quest-4",
    title: "Quiz Master",
    description: "Score 90% or above on 2 quizzes",
    type: "daily",
    xp: 200,
    coins: 40,
    target: 2,
    icon: "🎯",
    tags: ["quiz", "performance"],
  },
  {
    id: "quest-5",
    title: "Streak Champion",
    description: "Maintain a 7-day learning streak",
    type: "weekly",
    xp: 500,
    coins: 100,
    target: 7,
    icon: "🔥",
    tags: ["streak", "consistency"],
  },
  {
    id: "quest-6",
    title: "Social Learner",
    description: "Join a study group and participate in 3 sessions",
    type: "weekly",
    xp: 350,
    coins: 70,
    target: 3,
    icon: "👥",
    tags: ["social", "study-group"],
  },
  {
    id: "quest-7",
    title: "Duel Champion",
    description: "Win 5 duels against other learners",
    type: "epic",
    xp: 800,
    coins: 200,
    target: 5,
    icon: "⚡",
    tags: ["duel", "pvp"],
  },
];

export const SEED_JOBS: Job[] = [
  {
    id: "job-1",
    title: "Frontend Developer",
    company: "TechCorp India",
    location: "Bangalore, India",
    type: "full-time",
    salary: "₹8L – ₹15L",
    description: "Build scalable React applications for millions of users. Work with a passionate team on cutting-edge products.",
    requirements: ["React", "TypeScript", "CSS", "REST APIs", "Git"],
    posted: "2026-04-20T00:00:00.000Z",
    tags: ["react", "frontend", "typescript"],
    logoUrl: "https://ui-avatars.com/api/?name=TechCorp&background=6366f1&color=fff",
  },
  {
    id: "job-2",
    title: "Data Scientist Intern",
    company: "Analytics Pro",
    location: "Remote",
    type: "internship",
    salary: "₹25K/month",
    description: "Apply ML models to real business problems. Work directly with senior data scientists on live projects.",
    requirements: ["Python", "Pandas", "Scikit-learn", "Statistics", "SQL"],
    posted: "2026-04-18T00:00:00.000Z",
    tags: ["python", "data-science", "ml"],
    logoUrl: "https://ui-avatars.com/api/?name=Analytics+Pro&background=10b981&color=fff",
  },
  {
    id: "job-3",
    title: "Backend Engineer",
    company: "StartupXYZ",
    location: "Delhi, India",
    type: "full-time",
    salary: "₹10L – ₹18L",
    description: "Design and build robust APIs powering our fintech platform. Own services end-to-end from design to deployment.",
    requirements: ["Node.js", "PostgreSQL", "Docker", "AWS", "TypeScript"],
    posted: "2026-04-22T00:00:00.000Z",
    tags: ["nodejs", "backend", "postgresql"],
    logoUrl: "https://ui-avatars.com/api/?name=StartupXYZ&background=f59e0b&color=fff",
  },
  {
    id: "job-4",
    title: "UI/UX Designer",
    company: "DesignStudio",
    location: "Mumbai, India",
    type: "full-time",
    salary: "₹7L – ₹12L",
    description: "Shape the visual identity and user experience for a portfolio of SaaS products.",
    requirements: ["Figma", "User Research", "Prototyping", "CSS", "Design Systems"],
    posted: "2026-04-15T00:00:00.000Z",
    tags: ["design", "ux", "figma"],
    logoUrl: "https://ui-avatars.com/api/?name=DesignStudio&background=ec4899&color=fff",
  },
  {
    id: "job-5",
    title: "Full Stack Developer",
    company: "GlobalTech",
    location: "Hyderabad, India",
    type: "full-time",
    salary: "₹12L – ₹22L",
    description: "Own features from database to UI. Work in a fast-moving team shipping weekly.",
    requirements: ["React", "Node.js", "MongoDB", "TypeScript", "Redis"],
    posted: "2026-04-24T00:00:00.000Z",
    tags: ["fullstack", "react", "nodejs"],
    logoUrl: "https://ui-avatars.com/api/?name=GlobalTech&background=3b82f6&color=fff",
  },
  {
    id: "job-6",
    title: "ML Engineer",
    company: "AI Labs India",
    location: "Pune, India",
    type: "full-time",
    salary: "₹18L – ₹35L",
    description: "Build and productionize large-scale ML systems. Work on LLM fine-tuning and inference optimization.",
    requirements: ["Python", "TensorFlow", "PyTorch", "MLOps", "Kubernetes"],
    posted: "2026-04-21T00:00:00.000Z",
    tags: ["ml", "ai", "python", "tensorflow"],
    logoUrl: "https://ui-avatars.com/api/?name=AI+Labs&background=8b5cf6&color=fff",
  },
];

export const SEED_ACHIEVEMENTS: Achievement[] = [
  { id: "ach-1", name: "First Steps", description: "Complete your first lesson", icon: "👶", rarity: "common", xpReward: 50, condition: "complete_first_lesson" },
  { id: "ach-2", name: "Course Crusher", description: "Complete your first course", icon: "🎓", rarity: "rare", xpReward: 200, condition: "complete_first_course" },
  { id: "ach-3", name: "Quiz Ace", description: "Score 100% on any quiz", icon: "🎯", rarity: "rare", xpReward: 150, condition: "quiz_perfect_score" },
  { id: "ach-4", name: "Streak Master", description: "Maintain a 30-day streak", icon: "🔥", rarity: "epic", xpReward: 500, condition: "streak_30_days" },
  { id: "ach-5", name: "Polyglot", description: "Enroll in courses from 3 different categories", icon: "🌍", rarity: "rare", xpReward: 300, condition: "enroll_3_categories" },
  { id: "ach-6", name: "Duel Master", description: "Win 10 duels", icon: "⚔️", rarity: "epic", xpReward: 400, condition: "win_10_duels" },
  { id: "ach-7", name: "Legend", description: "Reach Level 20", icon: "👑", rarity: "legendary", xpReward: 1000, condition: "reach_level_20" },
  { id: "ach-8", name: "Social Butterfly", description: "Join 3 study groups", icon: "🦋", rarity: "common", xpReward: 100, condition: "join_3_groups" },
  { id: "ach-9", name: "Speed Learner", description: "Complete a course in under 3 days", icon: "⚡", rarity: "epic", xpReward: 350, condition: "fast_course_completion" },
  { id: "ach-10", name: "Night Owl", description: "Study for 1 hour after midnight", icon: "🦉", rarity: "common", xpReward: 75, condition: "night_study" },
];

export const SEED_MARKETPLACE: MarketplaceItem[] = [
  { id: "item-1", name: "XP Booster", description: "Double XP for 2 hours", price: 50, category: "boost", icon: "⚡", rarity: "common" },
  { id: "item-2", name: "Coin Magnet", description: "Earn 50% more coins for 24 hours", price: 80, category: "boost", icon: "🧲", rarity: "rare" },
  { id: "item-3", name: "Dark Knight Avatar", description: "Exclusive dark knight character skin", price: 200, category: "avatar", icon: "🗡️", rarity: "epic" },
  { id: "item-4", name: "Galaxy Theme", description: "Apply a stunning galaxy theme to your profile", price: 150, category: "theme", icon: "🌌", rarity: "rare" },
  { id: "item-5", name: "Golden Crown Badge", description: "Flex the golden crown on your profile", price: 500, category: "badge", icon: "👑", rarity: "legendary" },
  { id: "item-6", name: "Streak Shield", description: "Protect your streak for 1 day if you miss", price: 100, category: "powerup", icon: "🛡️", rarity: "common" },
  { id: "item-7", name: "Hint Token", description: "Get a hint in any quiz question", price: 30, category: "powerup", icon: "💡", rarity: "common" },
  { id: "item-8", name: "Cyber Ninja Avatar", description: "Futuristic ninja character skin", price: 300, category: "avatar", icon: "🥷", rarity: "epic" },
];
